site_name: TGX
site_url: https://github.com/fpour/TGX
nav:
    - Home: index.md
    - API: 
      - ReadWrite: 
        -  Read Data: io.md
      - Utils: 
        - Graph stats: utils/graph_stats.md
        - Graph Utils: utils/graph_utils.md
        - Plotting Utils: utils/plotting_utils.md
      - Visualization: 
        -  TEA Plot: viz/vis_tea.md
        -  TET Plot: viz/vis_tet.md
      - Classes: 
        - Graph: classes/graph.md
        - Datasets: classes/datasets.md
    - Tutorials:
      - Load data: tutorials/data_loader.ipynb
      - Generate TEA and TET plots: tutorials/TEA&TET.ipynb

    - Gallery:
      - Plots by type: 
        - TEA Plots: gallery/tea.md
        - TET Plots: gallery/tet.md
      - Plots by dataset: gallery/dataset.md


theme:
  name: material
  features:
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.tabs.sticky
    # - navigation.sections
    - navigation.expand
    # - toc.integrate
    # - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: navy
      accent: red
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: orange
      accent: lime


plugins: 
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
  - mkdocstrings:
      watch:
        - tgx/
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("docs")
            - sys.path.append("tgx")
          selection:
            new_path_syntax: true
          rendering:
            show_root_heading: false
            heading_level: 3
            show_root_full_path: false


  - mkdocs-jupyter:
      execute: false
#         handlers:
#           python:
#             paths: [.] 
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

# extra_javascript:
#   - javascripts/mathjax.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js