site_name: TGX
# site_url: https://github.com/fpour/TGX
nav:
    - Home: index.md
    - API: 
      - Classes: classes.md
      - Datasets: datasets.md
      - ReadWrite: readwrite.md
      - Utils: utils.md
      - Visualizations: vis.md

    - Tutorials:
      - Load data: tutorials/data_loader.ipynb
      - Generate TEA and TET plots: tutorials/TEA&TET.ipynb


theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: navy
      accent: red
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: orange
      accent: lime


plugins: 
  - mkdocstrings:
      # watch:
      #   - tgx/
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("docs")
            - sys.path.append("tgx")
          selection:
            new_path_syntax: true
          rendering:
            show_root_heading: false
            heading_level: 3
            show_root_full_path: false


  - mkdocs-jupyter:
      execute: false
#         handlers:
#           python:
#             paths: [.] 