site_name: TGX
site_url: https://github.com/fpour/TGX
nav:
    - Home: index.md
    - API: 
      - ReadWrite: 
        -  Read Data: io/io.md
      - Utils: 
        - Graph stats: utils/graph_stats.md
        - Graph Utils: utils/graph_utils.md
        - Plotting Utils: utils/plotting_utils.md
      - Visualization: 
        -  TEA Plot: viz/vis_tea.md
        -  TET Plot: viz/vis_tet.md
      - Classes: 
        - Graph: classes/graph.md
      - Data:
        - Builtin: data/builtin.md
        - TGB: data/tgb.md
    - Tutorials:
      - Load data: tutorials/data_loader.ipynb
      - Features: tutorials/Features.ipynb
      - Generate TEA and TET plots: tutorials/TEA&TET.ipynb

    - Gallery:
      - Plots by type: 
        - TEA Plots: 
          - Builtin: gallery/0-tea-builtin.md
          - TGB: gallery/0-tea-tgb.md
        - TET Plots: 
          - Builtin: gallery/0-tet-builtin.md
          - TGB: gallery/0-tet-tgb.md
        - Average degree over time: gallery/0-degree.md
        - Node and Edge over time: gallery/0-node_edge.md
      - Plots by dataset: 
        - Builtin:
          - Reddit: gallery/reddit.md
          - MOOC: gallery/mooc.md
          - LastFM: gallery/lastfm.md
          - Enron: gallery/enron.md
          - Social Evo: gallery/socialevo.md
          - UCI: gallery/uci.md
          - Flights: gallery/flight.md
          - Can Parl: gallery/canparl.md
          - US Legis: gallery/uslegis.md
          - UN Vote: gallery/unvote.md
          - Contacts: gallery/contact.md
        - TGB:
          - tgbl-wiki: gallery/tgbl-wiki.md
          - tgbl-review: gallery/tgbl-review.md
          - tgbl-coin: gallery/tgbl-coin.md
          - tgbl-comment: gallery/tgbl-comment.md
          - tgbl-flight: gallery/tgbl-flight.md
          - tgbn-trade: gallery/tgbn-trade.md
          - tgbn-genre: gallery/tgbn-genre.md
          - tgbn-reddit: gallery/tgbn-reddit.md


theme:
  name: material
  features:
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.tabs.sticky
    # - navigation.sections
    - navigation.expand
    # - toc.integrate
    # - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: navy
      accent: red
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: orange
      accent: lime


plugins: 
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
  - mkdocstrings:
      watch:
        - tgx/
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("docs")
            - sys.path.append("tgx")
          selection:
            new_path_syntax: true
          rendering:
            show_root_heading: false
            heading_level: 3
            show_root_full_path: false


  - mkdocs-jupyter:
      execute: false
#         handlers:
#           python:
#             paths: [.] 
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

# extra_javascript:
#   - javascripts/mathjax.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js